# ReadMe
## How to:

### Simply run test_array.py
### If all tests run successfully, you should see an output 'All tests successfully ran'
### If something goes wrong, an AssertionError will be raised and the specific test that failed will be included in the error message
## Examples:
### A successful run:
#### run test_array.py
>All tests successfully ran
## 
### An unsuccessful run:
#### run test_array.py
>AssertionError: Something went wrong with test_add_1d()